Repository florimondmanca/djangorestframework-api-key, pull requests merged in 2020-02, with the labels that each got.

#106 Refactor view_with_permissions as a utility function
  tests/conftest.py
  tests/test_permissions.py
  tests/test_permissions_combination.py
  tests/test_permissions_custom.py
  tests/utils.py
Labels: refactor

#108 Refactor admin tests
  tests/test_admin.py
Labels: refactor

#109 Refactor and type non-permission tests
  tests/test_checks.py
  tests/test_legacy_key_generator.py
Labels: refactor

#110 Freeze legacy key generator
  tests/test_legacy_key_generator.py
Labels: refactor

#105 Add Windows tooling compatibility
  .travis.yml
  scripts/check
  scripts/docs
  scripts/env
  scripts/install
  scripts/lint
  scripts/publish
  scripts/serve
  scripts/test
Labels: enhancement, tooling

#93 Add and document BaseAPIKeyManager.get_from_key()
  CHANGELOG.md
  docs/guide.md
  src/rest_framework_api_key/models.py
  tests/test_model.py
Labels: enhancement
