Repository florimondmanca/djangorestframework-api-key, pull requests merged in 2021-09, with the labels that each got.

#178 Format code under tests/
  scripts/check
  scripts/lint
  tests/test_admin.py
  tests/test_model.py
  tests/test_permissions.py
  tests/test_permissions_combination.py
  tests/test_permissions_custom.py
  tests/utils.py
Labels: tooling

#179 Update CI templates to 3.4
  ci/azure-pipelines.yml
Labels: tooling

#175 Add support for custom API keyword
  docs/guide.md
  src/rest_framework_api_key/permissions.py
  tests/test_model.py
  tests/test_permissions.py
Labels: enhancement

#182 Publish to PyPI automatically
  CONTRIBUTING.md
  ci/azure-pipelines.yml
  requirements.txt
  scripts/build
  scripts/clean
  scripts/publish
Labels: tooling

#183 Deploy docs manually
  CONTRIBUTING.md
  scripts/publish
Labels: docs, tooling
